### ISSUE TITLE
Getting 500 error when trying to get mail from POP3

### ISSUE THREAD

**Issue by Phoenie1** [controlscanmdr/cyphon#456]
I've set up a mailbox to get mail from an Exchange account using POP3.  URI is:  "pop3://mycompany.cyphon:accountpassword@mailhost.mycompany.net".  The mailbox isn't polling, and when I check the box on the mailbox page and use the "Get new mail" utility at the bottom of the page, I get "Server Error (500)" back.  I've tested getting mail from this account and this mailhost using Python utilities and it works just fine.

**Comment by lhadjchikh** [comment]
If you're using a Docker deployment (e.g., Cyphondock or ISO install), can you check the logs for the `cyphondock_cyphon_1` and `cyphondock_celeryworker_1` containers to see what caused the 500 error? E.g.:
```
docker logs -f cyphondock_cyphon_1
```
The `cyphondock_celeryworker_1` container is responsible for checking mail on a schedule, but since you checked the mailbox manually, the error will probably appear in the logs of the `cyphondock_cyphon_1` container instead. (NOTE: If the above command doesn't work, try using `sudo`.)

**Comment by santi10** [comment]
Great, I go to research it. 

Thx!!

**Comment by santi10** [comment]
Yes, I've solved this issue. Thanks you!!!!

**Comment by Phoenie1** [comment]
The output

BTW, I can't find a /var/mail/.aeris.cyphon.pop in any container.

sudo docker logs -f cyphondock_cyphon_1
Running Production Server
Running Production Server
ERROR Internal Server Error: /admin/django_mailbox/mailbox/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1568, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1286, in response_action
    response = func(self, request, queryset)
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/admin.py", line 26, in get_new_mail
    mailbox.get_new_mail()
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 409, in get_new_mail
    connection = self.get_connection()
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 215, in get_connection
    conn.connect(self.username, self.password)
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/transports/pop3.py", line 24, in connect
    self.server.pass_(password)
  File "/usr/local/lib/python3.6/poplib.py", line 213, in pass_
    return self._shortcmd('PASS %s' % pswd)
  File "/usr/local/lib/python3.6/poplib.py", line 176, in _shortcmd
    return self._getresp()
  File "/usr/local/lib/python3.6/poplib.py", line 152, in _getresp
    raise error_proto(resp)
poplib.error_proto: b'-ERR [IN-USE] /var/mail/.aeris.cyphon.pop lock busy!  Is another session active? (11)'
