### ISSUE TITLE
Cyphon receiver not able to read data from RabbitMq-server

### ISSUE THREAD

**Issue by jaydeepvagadiya** [controlscanmdr/cyphon#534]
Hello Experts,

We have try to consume data from RabbitMq-Server using Cyphon Receiver but getting blow error:

(cyphon) root@ubuntu:/opt/cyphon# python ./cyphon/receiver/receiver.py watchdogs 4
/opt/cyphon/lib/python3.6/site-packages/psycopg2-2.7.4-py3.6-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "./cyphon/receiver/receiver.py", line 55, in <module>
    from sifter.datasifter.datachutes.models import DataChute
  File "/opt/cyphon/cyphon/sifter/datasifter/datachutes/models.py", line 27, in <module>
    from aggregator.pipes.models import Pipe
  File "/opt/cyphon/cyphon/aggregator/pipes/models.py", line 31, in <module>
    from aggregator.reservoirs.models import Reservoir
  File "/opt/cyphon/cyphon/aggregator/reservoirs/models.py", line 27, in <module>
    from ambassador.platforms.models import Platform, PlatformManager
  File "/opt/cyphon/cyphon/ambassador/platforms/models.py", line 33, in <module>
    from platforms.registry import PLATFORM_CHOICES
  File "/opt/cyphon/cyphon/platforms/registry.py", line 30, in <module>
    from utils.choices import choices
  File "/opt/cyphon/cyphon/utils/choices/choices.py", line 30, in <module>
    from bottler.bottles.models import BottleField
  File "/opt/cyphon/cyphon/bottler/bottles/models.py", line 38, in <module>
    class BottleField(DataField):
  File "/opt/cyphon/cyphon/bottler/bottles/models.py", line 42, in BottleField
    embedded_doc = models.ForeignKey('Bottle', blank=True, null=True)
**TypeError: __init__() missing 1 required positional argument: 'on_delete'**

**Comment by jaydeepvagadiya** [comment]
This error is also getting from Cyphon Receiver 

(cyphon) root@ubuntu:/opt/cyphon# python ./cyphon/receiver/receiver.py watchdogs 4
Traceback (most recent call last):
  File "./cyphon/receiver/receiver.py", line 57, in <module>
    from watchdogs.models import Watchdog
  File "/opt/cyphon/cyphon/watchdogs/models.py", line 31, in <module>
    from alarms.models import Alarm, AlarmManager
  File "/opt/cyphon/cyphon/alarms/models.py", line 28, in <module>
    from alerts.models import Alert
  File "/opt/cyphon/cyphon/alerts/models.py", line 30, in <module>
    from ckeditor_uploader.fields import RichTextUploadingField
  File "/opt/cyphon/lib/python3.6/site-packages/django_ckeditor-5.4.0-py3.6.egg/ckeditor_uploader/fields.py", line 3, in <module>
    from ckeditor import fields
  File "/opt/cyphon/lib/python3.6/site-packages/django_ckeditor-5.4.0-py3.6.egg/ckeditor/fields.py", line 6, in <module>
    from .widgets import CKEditorWidget
  File "/opt/cyphon/lib/python3.6/site-packages/django_ckeditor-5.4.0-py3.6.egg/ckeditor/widgets.py", line 54, in <module>
    class CKEditorWidget(forms.Textarea):
  File "/opt/cyphon/lib/python3.6/site-packages/django_ckeditor-5.4.0-py3.6.egg/ckeditor/widgets.py", line 59, in CKEditorWidget
    class Media:
  File "/opt/cyphon/lib/python3.6/site-packages/django_ckeditor-5.4.0-py3.6.egg/ckeditor/widgets.py", line 68, in Media
    static('ckeditor/ckeditor/'),
  File "/opt/cyphon/lib/python3.6/site-packages/django_js_asset-1.1.0-py3.6.egg/js_asset/js.py", line 17, in static
    return staticfiles_storage.url(path)
  File "/opt/cyphon/lib/python3.6/site-packages/django_s3_storage-0.12.4-py3.6.egg/django_s3_storage/storage.py", line 389, in url
  File "/opt/cyphon/lib/python3.6/site-packages/botocore/signers.py", line 576, in generate_presigned_url
    params = self._emit_api_params(params, operation_model, context)
  File "/opt/cyphon/lib/python3.6/site-packages/botocore/client.py", line 648, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/opt/cyphon/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/opt/cyphon/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/opt/cyphon/lib/python3.6/site-packages/botocore/handlers.py", line 217, in validate_bucket_name
    if VALID_BUCKET.search(bucket) is None:
**TypeError: expected string or bytes-like object**

**Comment by lhadjchikh** [comment]
Hi @jaydeepvagadiya, how is Cyphon installed? Did you use Cyphondock, the installer ISO, or did you install it manually?  Regarding `TypeError: init() missing 1 required positional argument: 'on_delete'`, I think I've seen that error when trying to use Cyphon with Django 2.0, which requires that attribute be defined on ForeignKey fields. We haven't yet updated all of our models for compatibility with Django 2.0 yet, so please confirm you're using Django 1.11 as a first step...
