### ISSUE TITLE
Django Variable "cyphon.settings.default" not set up properly

### ISSUE THREAD

**Issue by LosaMatova** [controlscanmdr/cyphon#688]
When following the manual instruction settings found here: 
https://cyphon.readthedocs.io/en/latest/getting-started/install-cyphon.html

After configuring the conf.py, prod.py, base.py files (Which has to be taken from cyphondock due to to https://github.com/dunbarcyber/cyphon/issues/687#issue-397272690), the following step is to run:
`python3 setup.py install`
`python3 manage.py migrate`

Which will throw the following:

```
An error occurred while closing Streams: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

Traceback (most recent call last):
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cyphon/manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 81, in handle
    connection.prepare_database()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 25, in prepare_database
    with self.cursor() as cursor:
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/cyphon/virtualenvs/cyphon/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"
```

As DJango is falling back on `django/db/backends/postgresql/base.py` since `settings.cyphondock.default` has not been set correctly to have django use `./cyphon/settings/`

I haven't been able to solve this issue, and as such, I am currently roadblocked on the installation.

**Comment by LosaMatova** [comment]
Solved: See https://github.com/dunbarcyber/cyphon/issues/687#issuecomment-452795368

The correct value for manual installation is `cyphon.settings.conf` as per an explination found here: https://stackoverflow.com/questions/23156500/set-django-settings-module-as-an-environment-variable-in-windows-permanently/23157955#23157955 about how Django works.
